/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.IOException;
import java.io.PrintWriter;
import java.net.URLEncoder;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.tomcat.util.codec.binary.Base64;

/**
 *
 * @author gazda
 */
@WebServlet(urlPatterns = {"/registrationServlet"})
public class registrationServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if felh_nev servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if felh_nev servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if felh_nev servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        System.out.println("Dopost kezdes");
        response.setContentType("text/html");

        PrintWriter out = response.getWriter();
        String felh_nev = request.getParameter("felh_nev");
        String jelszo = request.getParameter("jelszo");
        String nev1 = request.getParameter("vnev");
        String nev2 = request.getParameter("knev");

        String email = request.getParameter("email");
        String tel_szam = request.getParameter("tel_szam");
        String varos = request.getParameter("varos");
        String utca = request.getParameter("utca");
        String hazszam = request.getParameter("hazszam");
        String szul_dat = request.getParameter("szul_dat");
        String checkboxes = request.getParameter("checkboxes");

        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver is loaded");

            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/webshop_db", "root", "");
            System.out.println("Connection created");

            PreparedStatement ps = con.prepareStatement("insert into felhasznalok(felh_nev, jelszo,vnev,knev ,email,tel_szam , varos , utca ,hazszam ,szul_dat , checkboxes ) values (?,?,?,?,?,?,?,?,?,?,?)");
            System.out.println("atment1");
//            ResultSet rs = ps.getGeneratedKeys();
//
//            rs.next();
//            int autoGeneratedID = rs.getInt(1);
//            
//            
//            ps.setInt(1, autoGeneratedID);
//            ps.setInt(1, null);
            System.out.println("nullon atment");
            ps.setString(1, felh_nev);
            ps.setString(2, jelszo);
            ps.setString(3, nev1);
            ps.setString(4, nev2);
            ps.setString(5, email);
            ps.setString(6, tel_szam);
            ps.setString(7, varos);
            ps.setString(8, utca);
            ps.setString(9, hazszam);
            ps.setString(10, szul_dat);
            ps.setString(11, checkboxes);
            System.out.println("feltoltes elott");

            ps.executeUpdate();
            System.out.println("feltoltes megvolt");

            ps.close();
            con.close();
            System.out.println("Zárva a connection és a ps");
            out.close();

            System.out.println("Inserted");

        } catch (Exception e1) {

            System.out.println(e1);
            System.err.println("Got an exception!");

        }

        /*
        
        response.setContentType("text/html;charset=UTF-8");
        String felh_nev,jelszo,email,d,tel_szam,f,g,h,i,name="";
        PrintWriter out = response.getWriter();
        request.setCharacterEncoding("UTF-8");
            
        if(!request.getParameter("felh_nev").isEmpty())
        {
            felh_nev=request.getParameter("felh_nev").toString();
            jelszo=request.getParameter("jelszo").toString();
            email=request.getParameter("email").toString();
            d=request.getParameter("tel_szam").toString();
            tel_szam=request.getParameter("varos").toString();
            f=request.getParameter("utca").toString();
            g=request.getParameter("hazszam").toString();
            h=request.getParameter("szuldat").toString();
            i=request.getParameter("checkboxes").toString();

            
//            i=request.getParameter("iar").toString();
            
            
            felvisz(felh_nev,jelszo,email,d,tel_szam,f,g,h,i);
            
        }
           
            out.println("</body>");
            out.println("</html>");
            
            response.sendRedirect("piroskaS?name="+URLEncoder.encode(name,"UTF-8"));*/
    }

    String kezdolap() {
        String g = "";

        return g;
    }

    void felvisz(String a, String b, String c, String d, String e, String f, String g, String h, String i) {
        /*try {
            String s = "";
            String y = "";
            ResultSet rs = null;
            String x = "";
            String id,id1;
            indit in = new indit();
            in.startConnection("");
            //byte[] encoded = Base64.encodeBase64(tel_szam.getBytes());
            
            x = "insert into felhasznalo values(null,'" + felh_nev + "','" + jelszo + "','" + email + "','" + d + "');";
            in.leker(x, 1);
            s = "select last_insert_id();";
            rs = in.leker(s, 0);
            rs.next();
            id = rs.getString(1);
           
            y = "insert into beosztas values(null,'" + tel_szam + "','" + f + "','" + g + "','" + h + "','"+ id +"');";
            in.leker(y, 1);
//            s = "select last_insert_id();";
//            rs = in.leker(s, 0);
//            rs.next();
//            id1 = rs.getString(1);
            
            
//            x = "insert into ig values(null,'" + tel_szam + "','" + f + "','" + g + "','" + h + "','" + i + "','" + j + "','" + k + "','" + l+ "','" + id + "','" + id1 + "');";
//            in.leker(x, 1);
         
            //rs.next();
            //id = rs.getString(1);
            
            
            
            //rs.next();
            //id = rs.getString(1);
            create user  name GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `webshop_db`.* TO name@'%';
             
        }@'%';
             
        } catch (SQLException ex) {
            Logger.getLogger(registrationServlet.class.getName()).log(Level.SEVERE, null, ex);
        }*/

    }

    /**
     * Returns felh_nev short description of the servlet.
     *
     * @return felh_nev String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}
